version: "3.9"

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database_postgresql
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=database_postgresql
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=devpass
    ports:
      - 8000:8000
    volumes:
      - ./src:/app

  database_postgresql:
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
    image: postgres:alpine3.18
    ports:
      - 5432:5432